//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeliculaWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public System.Guid idPelicula { get; set; }
        public string Titulo { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Genero { get; set; }
    }
}
